//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrydayBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrations
    {
        public int IntegrationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IntegrationType { get; set; }
        public string IntegrationDetails { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
