//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrydayBook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EverydayBookEntities1 : DbContext
    {
        private static EverydayBookEntities1 _context;
        public static EverydayBookEntities1 GetContext()
        {
            return new EverydayBookEntities1();
        }

        public EverydayBookEntities1()
            : base("name=EverydayBookEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Birthdates> Birthdates { get; set; }
        public virtual DbSet<Integrations> Integrations { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
