//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrydayBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<System.TimeSpan> NotificationTime { get; set; }
        public string NotificationType { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
